[variables]
NODE_ENV = "production"
AUTHENTICATION_API_KEY = "whatsapp_saas_evolution_prod_key_2024"
SERVER_PORT = "8080"

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[start]
cmd = "npm start"

[phases.post-build]
cmds = ["echo 'Evolution API build completed successfully'"]