[variables]
NODE_ENV = "production"

[phases.install]
dependsOn = ["setup"]
cmds = ["npm ci"]

[phases.build]
dependsOn = ["install"]
cmds = ["npm run build"]

[phases.setup]
nixPkgs = ["nodejs-18_x", "npm-9_x"]

[start]
cmd = "npm run preview"

[staticAssets]
dir = "dist"

[phases.post-build]
cmds = ["echo 'Frontend build completed successfully'"]